### ISSUE TITLE
Document POST API on Swagger

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#19]
- Find the POST Opportunity API and write YAML documentation for it. 
- [Text Documentation](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/blob/develop/documentation/APIS.md) for reference

**Comment by Haneesha123** [comment]
I want to work on this issue as part of GSSOC21

**Comment by Manvityagi** [comment]
> I want to work on this issue as part of GSSOC21

Assigned to you @Haneesha123

**Comment by Haneesha123** [comment]
@Manvityagi Can you give me a detailed explanation on this issue? It is not clear.

**Comment by abdus** [comment]
hey @Haneesha123, we have some API endpoints ready. We are going to use [Swagger](https://swagger.io/) for API documentation. So, the issue is about writing documentations for those endpoints. 
Your task: find out the `POST /opportunity`(`/opportunity` endpoint for adding new opportunities) endpoint and document it in a way that is compatible with Swagger.

PS: I finished setting up Swagger for this project. Unfortunately, I forgot to push it. You can either wait until I push it. Or you can do the set-up by yourself. If you choose the latter option, please use these packages: [`swagger-ui-express`](https://www.npmjs.com/package/swagger-ui-express) and [`swagger-jsdoc`](https://www.npmjs.com/package/swagger-jsdoc)(please use version 6xx. 7xx is not compatible with `require()`)

If you need further assistance, you can reply here or use Discord. My Discord tag is `Abdus#1541`.

**Comment by Haneesha123** [comment]
Okay. I will wait until you push it @abdus

**Comment by abdus** [comment]
Pushed. you can start working. @Haneesha123

**Comment by Haneesha123** [comment]
@Manvityagi @abdus Can you check if this is ok? If yes, I will proceed to create a pull request.
![Capture](https://user-images.githubusercontent.com/61455329/112278045-69104380-8ca8-11eb-80bb-9c4baa4c3a64.PNG)
![Capture1](https://user-images.githubusercontent.com/61455329/112279304-cb1d7880-8ca9-11eb-93b2-2d3dd3a60d12.PNG)
![Capture2](https://user-images.githubusercontent.com/61455329/112278043-69104380-8ca8-11eb-9452-9bd205c1c0c5.PNG)

**Comment by abdus** [comment]
@Haneesha123 open a PR. that way, I would be able to pull changes locally and test.

**Comment by Haneesha123** [comment]
@abdus  I have opened PR #24. Please check it.
